### ISSUE TITLE
Создание ивента

### ISSUE THREAD

**Issue by EeOneDown** [hiking-heroes/Backlog#16]
Аналогично https://github.com/hiking-heroes/Backlog/issues/12#issue-362969667
- [x] Server
- [x] Mobile
- [x] Integration

**Comment by EeOneDown** [comment]
@AlexKornShell 
Надо придумать форму заполнения ивента - какие поля будут?

**Comment by AlexKornShell** [comment]
Поля, подгружаемые с карты - это координаты lat и lng. На сервере также это ивент привязывается к конкретному пользователю - автору.
В форме заполняются: Title, start (дата и время), end (дата и время), 
public/private, для private - окошечко invited, куда пишутся email'ы тех, кого приглашаешь,
seats с количеством мест (ну и собственно, на сервере должно быть ещё количество свободных),
description с описанием, webSite с ссылкой на сайт,
gallery с фотографиями (но это уже такое - надо ещё научиться подгружать),
tags с хэштегами.
А так - надо ещё что-то посмотреть у Navi, потому как у них много клёвого сделано.
